version: 0.1

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --region $AWS_REGION)
  build:
    commands:
      - docker build -t $APP_IMAGE .
      - docker push $APP_IMAGE
  post_build:
    commands:
      - echo Build completed on `date`
