version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=770197195015.dkr.ecr.us-east-1.amazonaws.com/cicd-node:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      #- IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
       - echo Build started on `date`
       - echo Building the Docker image...
       - docker build -t cicd-node .
       - docker tag cicd-node:latest 770197195015.dkr.ecr.us-east-1.amazonaws.com/cicd-node:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 770197195015.dkr.ecr.us-east-1.amazonaws.com/cicd-node:latest
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-node","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json
